# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8088
#spring
spring:
  # 指定静态资源的路径
  resources:
    static-locations: classpath:/static/,classpath:/views/,file:${web.upload},file:${web.ueditorUpload}
  datasource:
    #driver-class-name: org.sqlite.JDBC
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    #driver-class-name: org.postgresql.Driver
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 方式一：  引用外部文件
    #        url: jdbc:sqlite:D:/eclipse/xy.db
    #方式二： 引用项目中的文件
    #url: jdbc:sqlite::resource:static/sqlite/xy.db
    #url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #url: jdbc:oracle:thin:@ip:1521:dev
    #url: jdbc:postgresql://localhost:5432/postgres
    #url: jdbc:sqlserver://localhost:1433;DatabaseName=localdemo
    url: jdbc:mysql://localhost:3306/producttest?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username:
    password:

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  #configLocation: classpath:mybatis.xml
# sql打印
logging:
  level: debug
  level.com.xuanyin: debug
  path: logs/
#    file: admin.log