#不了解 则 直接 模仿 k8s 组件配置
---
#api 版本
apiVersion: apps/v1
#资源类型
kind: Deployment
#资源元数据
metadata:
  name: kube-eureka-server-ds
  namespace: kube-system
  labels:
    tier: node
    app: eureka-server
#资源规格    
spec:
  #标签选择器
  selector:
    matchLabels:
      app: eureka-server
  #pod模板    
  template:
    #pod元数据
    metadata:
      labels:
        tier: node
        app: eureka-server
    #pod 规格    
    spec:
      #容器配置
      containers:
      - command:
        - java eureka-server.jar
        - --port=4004
        - --name=eureka-server
        - --redisHost=192.168.1.3
        - --redisPort=6379
        - --redisPassword=wjp930514.
        - -Dhostname=0.0.0.0
        - --defaultZone=http://192.168.1.3:4001/eureka/,http://192.168.1.3:4002/eureka/
        - --register-with-eureka=false
        - fetch-registry=false
        image: eureka-server:v1
        ports: 
          - containerPort: 4004
        name: eureka-server  
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
