// <auto-generated />
using System;
using Comment.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Utility.Ef.Demo.Migrations.Comment
{
    [DbContext(typeof(CommentDbContent))]
    [Migration("20210827161738_a7")]
    partial class a7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Comment.Domain.Entities.CommentType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("t_akka_comment_type");
                });

            modelBuilder.Entity("Comment.Domain.Entities.Comments", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("account");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("Nickname")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.Property<long>("OrderDetailID")
                        .HasMaxLength(36)
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_detail_id");

                    b.Property<long>("OrderID")
                        .HasMaxLength(36)
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductID")
                        .HasMaxLength(36)
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<string>("Reply")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("reply");

                    b.Property<int>("Star")
                        .HasColumnType("INTEGER")
                        .HasColumnName("star");

                    b.Property<bool>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("t_akka_comment");
                });
#pragma warning restore 612, 618
        }
    }
}
