/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.99.101 8080 em
 Source Server Type    : Oracle
 Source Server Version : 120100
 Source Host           : 192.168.99.101:1521
 Source Schema         : TEST

 Target Server Type    : Oracle
 Target Server Version : 120100
 File Encoding         : 65001

 Date: 07/11/2020 23:02:50
*/


-- ----------------------------
-- Table structure for APIRESOURCEPROPERTIES
-- ----------------------------
DROP TABLE "TEST"."APIRESOURCEPROPERTIES";
CREATE TABLE "TEST"."APIRESOURCEPROPERTIES" (
  "ID" NUMBER(11) VISIBLE NOT NULL ,
  "KEY" VARCHAR2(250 BYTE) VISIBLE NOT NULL ,
  "VALUE" VARCHAR2(2000 BYTE) VISIBLE NOT NULL ,
  "APIRESOURCEID" NUMBER(11) VISIBLE NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Primary Key structure for table APIRESOURCEPROPERTIES
-- ----------------------------
ALTER TABLE "TEST"."APIRESOURCEPROPERTIES" ADD CONSTRAINT "SYS_C0010079" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table APIRESOURCEPROPERTIES
-- ----------------------------
ALTER TABLE "TEST"."APIRESOURCEPROPERTIES" ADD CONSTRAINT "SYS_C0010075" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."APIRESOURCEPROPERTIES" ADD CONSTRAINT "SYS_C0010076" CHECK ("KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."APIRESOURCEPROPERTIES" ADD CONSTRAINT "SYS_C0010077" CHECK ("VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."APIRESOURCEPROPERTIES" ADD CONSTRAINT "SYS_C0010078" CHECK ("APIRESOURCEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
